apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ .Chart.Name }}-config
  labels:
    {{- include "project.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.configMapVals }}
  {{ $key | quote | indent 6}}: {{ $val | quote }}
  {{- end}}