apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}-master
  labels:
    appname: {{ .Values.global.appname }}
    app: {{ template "redis.fullname" . }}
    role: master
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "redis.fullname" . }}
    role: master
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}


