apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}-slave
  labels:
    appname: {{ .Values.global.appname }}
    app: {{ template "redis.fullname" . }}
    role: slave
  {{- include "redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "redis.fullname" . }}
    role: slave
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: redis


